### ISSUE TITLE
How RNNs is implemented to learn the incoming influence in your IALS in this repository?

### ISSUE THREAD

**Issue by Yangli0505** [INFLUENCEorg/IAOP#1]
RNN implementation in this repository

**Comment by JINKEHE** [comment]
Hi,

The learning of incoming influence is described in the supplementary material of our paper under Section 7.1: 

https://proceedings.neurips.cc/paper/2020/file/2e6d9c6052e99fcdfa61d9b9da273ca2-Supplemental.pdf
